/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserPlan = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
  'elite' : IDL.Null,
});
export const PlayerProfile = IDL.Record({
  'coins' : IDL.Nat,
  'plan' : UserPlan,
  'level' : IDL.Nat,
  'lives' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'highScore' : IDL.Nat,
  'purchasedUpgrades' : IDL.Vec(IDL.Nat),
});
export const LevelConfig = IDL.Record({
  'enemyCount' : IDL.Nat,
  'difficulty' : IDL.Nat,
  'index' : IDL.Nat,
  'enemyTypes' : IDL.Text,
  'speedMultiplier' : IDL.Float64,
});
export const Upgrade = IDL.Record({
  'id' : IDL.Nat,
  'maxLevel' : IDL.Nat,
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ProfileUpdate = IDL.Record({
  'coins' : IDL.Nat,
  'level' : IDL.Nat,
  'lives' : IDL.Nat,
  'score' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getLevelConfig' : IDL.Func([IDL.Nat], [LevelConfig], ['query']),
  'getProfile' : IDL.Func([], [PlayerProfile], ['query']),
  'getUpgrades' : IDL.Func([], [IDL.Vec(Upgrade)], ['query']),
  'getUserPlan' : IDL.Func([], [UserPlan], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseUpgrade' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProgress' : IDL.Func([ProfileUpdate], [], []),
  'setPlan' : IDL.Func([IDL.Principal, UserPlan], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserPlan = IDL.Variant({
    'pro' : IDL.Null,
    'free' : IDL.Null,
    'elite' : IDL.Null,
  });
  const PlayerProfile = IDL.Record({
    'coins' : IDL.Nat,
    'plan' : UserPlan,
    'level' : IDL.Nat,
    'lives' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'highScore' : IDL.Nat,
    'purchasedUpgrades' : IDL.Vec(IDL.Nat),
  });
  const LevelConfig = IDL.Record({
    'enemyCount' : IDL.Nat,
    'difficulty' : IDL.Nat,
    'index' : IDL.Nat,
    'enemyTypes' : IDL.Text,
    'speedMultiplier' : IDL.Float64,
  });
  const Upgrade = IDL.Record({
    'id' : IDL.Nat,
    'maxLevel' : IDL.Nat,
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ProfileUpdate = IDL.Record({
    'coins' : IDL.Nat,
    'level' : IDL.Nat,
    'lives' : IDL.Nat,
    'score' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getLevelConfig' : IDL.Func([IDL.Nat], [LevelConfig], ['query']),
    'getProfile' : IDL.Func([], [PlayerProfile], ['query']),
    'getUpgrades' : IDL.Func([], [IDL.Vec(Upgrade)], ['query']),
    'getUserPlan' : IDL.Func([], [UserPlan], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseUpgrade' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProgress' : IDL.Func([ProfileUpdate], [], []),
    'setPlan' : IDL.Func([IDL.Principal, UserPlan], [], []),
  });
};

export const init = ({ IDL }) => { return []; };