/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LevelConfig {
  'enemyCount' : bigint,
  'difficulty' : bigint,
  'index' : bigint,
  'enemyTypes' : string,
  'speedMultiplier' : number,
}
export interface PlayerProfile {
  'coins' : bigint,
  'plan' : UserPlan,
  'level' : bigint,
  'lives' : bigint,
  'totalScore' : bigint,
  'highScore' : bigint,
  'purchasedUpgrades' : Array<bigint>,
}
export interface ProfileUpdate {
  'coins' : bigint,
  'level' : bigint,
  'lives' : bigint,
  'score' : bigint,
}
export interface Upgrade {
  'id' : bigint,
  'maxLevel' : bigint,
  'cost' : bigint,
  'name' : string,
  'description' : string,
}
export type UserPlan = { 'pro' : null } |
  { 'free' : null } |
  { 'elite' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<PlayerProfile>>,
  'getLevelConfig' : ActorMethod<[bigint], LevelConfig>,
  'getProfile' : ActorMethod<[], PlayerProfile>,
  'getUpgrades' : ActorMethod<[], Array<Upgrade>>,
  'getUserPlan' : ActorMethod<[], UserPlan>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseUpgrade' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProgress' : ActorMethod<[ProfileUpdate], undefined>,
  'setPlan' : ActorMethod<[Principal, UserPlan], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];